### PR TITLE
Add gmail email alerts and auto-redeem giftcards

### PR DESCRIPTION
**Pull request by dmarts05**
Hi, I have been working on a way of automatically redeeming points for gift cards, it defaults to Amazon gift cards but you can specify in accounts.json the gift card you want your account to redeem. 

I have also implemented gmail email alerts when an account has been locked, banned, a phone number verification is required or when an account redeems a reward.

Both these features are optional and can be enabled with --emailalerts and --redeem parameters.

I would also like to credit @Pre-mium (github profile in the updated README) for its auto-redeeming code, which proved very helpful when making this feature.

IMPORTANT: I have not yet tested if it correctly redeems because none of my accounts have reached the minimum points required for a gift card. I would really appreciate any feedback regarding this.

### CODE REVIEW

**Comment by dmarts05** [comment]
I have introduced new features to this pull request, please review the updated title and description.

**Comment by TheRedM** [comment]
> Hi, I have been working on a way of automatically redeeming points for gift cards, it defaults to Amazon gift cards but you can specify in accounts.json the gift card you want your account to redeem. 
> 
> I have also implemented gmail email alerts when an account has been locked, banned or when an account redeems a reward.
> 
> Both these features are optional and can be enabled with --emailalerts and --redeem parameters.
> 
> I would also like to credit @Pre-mium (github profile in the updated README) for its auto-redeeming code, which proved very helpful when making this feature.
> 
> IMPORTANT: I have not yet tested if it correctly redeems because none of my accounts have reached the minimum points required for a gift card. I would really appreciate any feedback regarding this.

Cool, but I think a telegram/discord bot is way better and easy to implement, I already made a little script that checks for daily points changes and send notification containing gained points.

**Comment by dmarts05** [comment]
> > Hi, I have been working on a way of automatically redeeming points for gift cards, it defaults to Amazon gift cards but you can specify in accounts.json the gift card you want your account to redeem.
> > I have also implemented gmail email alerts when an account has been locked, banned or when an account redeems a reward.
> > Both these features are optional and can be enabled with --emailalerts and --redeem parameters.
> > I would also like to credit @Pre-mium (github profile in the updated README) for its auto-redeeming code, which proved very helpful when making this feature.
> > IMPORTANT: I have not yet tested if it correctly redeems because none of my accounts have reached the minimum points required for a gift card. I would really appreciate any feedback regarding this.
> 
> Cool, but I think a telegram/discord bot is way better and easy to implement, I already made a little script that checks for daily points changes and send notification containing gained points.

That seems like a great idea! We could even have all these three methods implemented. I chose emails instead of other methods because I check emails more frequently, but I'll surely try to add those too.

**Comment by TheRedM** [comment]
> > > Hi, I have been working on a way of automatically redeeming points for gift cards, it defaults to Amazon gift cards but you can specify in accounts.json the gift card you want your account to redeem.
> > > I have also implemented gmail email alerts when an account has been locked, banned or when an account redeems a reward.
> > > Both these features are optional and can be enabled with --emailalerts and --redeem parameters.
> > > I would also like to credit @Pre-mium (github profile in the updated README) for its auto-redeeming code, which proved very helpful when making this feature.
> > > IMPORTANT: I have not yet tested if it correctly redeems because none of my accounts have reached the minimum points required for a gift card. I would really appreciate any feedback regarding this.
> > 
> > Cool, but I think a telegram/discord bot is way better and easy to implement, I already made a little script that checks for daily points changes and send notification containing gained points.
> 
> That seems like a great idea! We could even have all these three methods implemented. I chose emails instead of other methods because I check emails more frequently, but I'll surely try to add those too.

About the redeeming part, note that some rewards (most of the important ones) requires a phone verification, so I think the script will fail a this point, probably implementing a way to verify by adding a phone number to accounts.json could help but I don't see how to send back the received verification code to Microsoft without using an app that checks for SMS coming from Microsoft and sending that code back to the server.

**Comment by dmarts05** [comment]
> > > > Hi, I have been working on a way of automatically redeeming points for gift cards, it defaults to Amazon gift cards but you can specify in accounts.json the gift card you want your account to redeem.
> > > > I have also implemented gmail email alerts when an account has been locked, banned or when an account redeems a reward.
> > > > Both these features are optional and can be enabled with --emailalerts and --redeem parameters.
> > > > I would also like to credit @Pre-mium (github profile in the updated README) for its auto-redeeming code, which proved very helpful when making this feature.
> > > > IMPORTANT: I have not yet tested if it correctly redeems because none of my accounts have reached the minimum points required for a gift card. I would really appreciate any feedback regarding this.
> > > 
> > > 
> > > Cool, but I think a telegram/discord bot is way better and easy to implement, I already made a little script that checks for daily points changes and send notification containing gained points.
> > 
> > 
> > That seems like a great idea! We could even have all these three methods implemented. I chose emails instead of other methods because I check emails more frequently, but I'll surely try to add those too.
> 
> About the redeeming part, note that some rewards (most of the important ones) requires a phone verification, so I think the script will fail a this point, probably implementing a way to verify by adding a phone number to accounts.json could help but I don't see how to send back the received verification code to Microsoft without using an app that checks for SMS coming from Microsoft and sending that code back to the server.

As far as I know, it is only required the first time you redeem a reward. In that case, the script sends you an email letting you know that you need to manually verify that.

After that first verification Microsoft shouldn't ask you anymore.

**Comment by gdrhzrd6e** [comment]
an auto verifying/redeem script should be separate from main program maybe make an apk
or somehow utilize phone link
one more great option 
fax machine bot thingy
call up it records number and redeems with that phone number
then you just say the verify code appears in notifications or you could use the press one for blablahblah press whats usually at help centers
and dadada verifyed
not sure how complicated this 
but would be awesome feature


could use anyones random phone while walking streets:)

**Comment by dmarts05** [comment]
> an auto verifying/redeem script should be separate from main program maybe make an apk or somehow utilize phone link one more great option fax machine bot thingy call up it records number and redeems with that phone number then you just say the verify code appears in notifications or you could use the press one for blablahblah press whats usually at help centers and dadada verifyed not sure how complicated this but would be awesome feature
> 
> could use anyones random phone while walking streets:)

This sadly is far from my current skills and knowledge. I'll have a look at it, especially phone bots, but I don't think that it is something that could be released as an app.

**Review by MehdiRtal — COMMENTED** [review]
Would be better if we include all the functions in the main file.

**Comment by dmarts05** [comment]
> Would be better if we include all the functions in the main file.

Sure, I will push those changes in 5 minutes.

**Comment by DimaRazb** [comment]
> As far as I know, it is only required the first time you redeem a reward.

Incorrect. I have used redeem script like this for more than 2 years and can tell that even though you could redeem a second (or other) item without verification, next time you have to provide SMS code.
I do believe there is no way to automate it.

**Comment by dmarts05** [comment]
> > As far as I know, it is only required the first time you redeem a reward.
> 
> Incorrect. I have used redeem script like this for more than 2 years and can tell that even though you could redeem a second (or other) item without verification, next time you have to provide SMS code. I do believe there is no way to automate it. So please do not hold your breath on it.

I guess it depends on the country you are running the script on, because that's not the case for me.

**Comment by DimaRazb** [comment]
Was running it in the US.

**Comment by dmarts05** [comment]
> Was running it in the US.

I ran multiple EU accounts, that might be it.

**Comment by MehdiRtal** [comment]
What formatter do you use?

**Comment by dmarts05** [comment]
> What formatter do you use?

Autopep8, but I'm having a lot of problems with it. Sometimes it puts tabs and sometimes it puts spaces. Sorry if that's causing inconsistency

**Comment by MehdiRtal** [comment]
Honestly I'd prefer to not change the whole file formatting but only for the changes. That keeps tracking changes easier.

**Comment by MehdiRtal** [comment]
Not the last one, but if it's possible try to not change any formatting on the original code.

**Comment by MehdiRtal** [comment]
Could you change it now so I can merge?

**Comment by dmarts05** [comment]
> Could you change it now so I can merge?

Sorry, what do you want me to change? I didn't understand you.

**Comment by MehdiRtal** [comment]
I asked if you could restore the formatting of the original code and only add the changes.

**Comment by TheRedM** [comment]
> > Was running it in the US.
> 
> I ran multiple EU accounts, that might be it.

I once redeemed using a phone number, what was weird it didn't ask for the code, there was a place for it but after putting the number it just loaded the page and got the reward, but before that I got the dns can't be resolved error on Chrome, I was using a vpn, and probably the vpn bugged for a moment, I think it's a vulnerability, if someone could confirm, it would be great to take advantage of that.

**Comment by dmarts05** [comment]
> I asked if you could restore the formatting of the original code and only add the changes.

Ok, I'll try to do that right now.

**Comment by dmarts05** [comment]
I might have left some minor changes I did regarding comments but I think the important stuff is there.

**Pull request merged**
