### PR TITLE
Changed cron job

### PR DESCRIPTION
**Pull request by DimaRazb**
Cron automatically ran only once, changed that.

### CODE REVIEW

**Comment by DerMuffin** [comment]
Every six hours? Why?

The Scripts runs perfectly fine if you run it one time. Maybe it can run every 12 hours. Just in case the first run failed.

What you think @MehdiRtal ?

**Comment by gdrhzrd6e** [comment]
he can just make his own branch

**Comment by gdrhzrd6e** [comment]
no one else needs this cause if it fails no point in rerunning just wastes the limited hours you got
you just have to fix the error

**Comment by mgrimace** [comment]
> Every six hours? Why?
> 
> The Scripts runs perfectly fine if you run it one time. Maybe it can run every 12 hours. Just in case the first run failed.
> 
> What you think @MehdiRtal ?

Agreed, I don't see any reason to run more than once every 12 hours by default. Relating to another thread, each person should probably customize their own cron needs anyways, default branch should stay 1x/12 hrs to avoid over-use (both for github limited hours, and for not hammering MS Rewards and risking detection).

For my use `cron: '0 10 * * *'  # every day at 6:00 am EST, 10:00 am UTC`

**Comment by DimaRazb** [comment]
The idea here is your time zone. When I ran default settings cron does not collect today's points- instead he does yesterday cycle. Tht's why I thought every 8 or 10 hours will be the best defaults.

**Comment by DimaRazb** [comment]
Well fine then, we could just update readme about this customization. I'm not suffering that I changed it, just thought that someone else will do the same.
That's why got a thought about changing defaults:
the script may fail, or time alone or etc. o harm to me to run it twice.

**Comment by mgrimace** [comment]
> Well fine then, we could just update readme about this customization. I'm not suffering that I changed it, just thought that someone else will do the same.
> That's why got a thought about changing defaults:
> the script may fail, or time alone or etc. o harm to me to run it twice.

Great idea, probably better solved through the readme under the *using github actions* instructions? e.g., add "github cron uses UTC timzone by default, be sure to customize cron to run once daily on your local timezone, e.g., `cron: '0 10 * * *'  # every day at 6:00 am EST, 10:00 am UTC`. Visit https://crontab.guru for details how to customize cron.

**Comment by DimaRazb** [comment]
Nice, love it. I use cron guru too!

**Pull request closed without merging**
