### PR TITLE
Improved email security and Discord webhook

### PR DESCRIPTION
**Pull request by Axel3026**
I'm having errors when running it on Windows with the webhook, apart from the fact that I don't understand anything about programming, I don't know how to fix it, if anyone knows what can be changed to make it work on the PC, it would be very helpful.

For the moment I would like them to only add the emails:

```
prYellow('********************' + account['username'][slice(0, 4)] + "**" + account['username'][slice(6, 7)] + '********************')
```

### CODE REVIEW

**Comment by Axel3026** [comment]
```.Json``` doesn't seem to detect any account, I don't know why

**Comment by Axel3026** [comment]
and to make it work you have to use --accounts

**Comment by gdrhzrd6e** [comment]
until its fixed this should work
https://anonfiles.com/m7C1MbKfya/MicrosoftRewardsBot_exe

**Comment by gdrhzrd6e** [comment]
its the older version

**Comment by gdrhzrd6e** [comment]
https://anonfiles.com/q3I1MeKay7/MicrosoftRewardsBot_exe current exe version

**Comment by gdrhzrd6e** [comment]
if you don't know. to use arguments
start asdhfsdkjfhksjdf.exe --headless in terminal or cmd

**Comment by MehdiRtal** [comment]
Why did you remove the email alerts feature?

**Comment by Axel3026** [comment]
@MehdiRtal It's just that gmail doesn't work for me, but maybe it does for you.
I found out that the error was on my PC since in github action it takes that argument well but the folder doesn't exist on the pc.
```
message = f'📅 Daily report {today} (N: {ARGS.wfd[0]})\n\n'

```
 (N: {ARGS.wfd[0]})\n\n'  When I created the message, this file does not exist on my PC, that's why it gave me an error, I don't know how to implement it so that it can be canceled on the PC, but on github if I take it

**Comment by MehdiRtal** [comment]
It would be better if you create another branch and only pull your new modifications.

**Pull request closed without merging**
