### PR TITLE
Add auth proxies support through selenium-wire

### PR DESCRIPTION
**Pull request by dmarts05**
You can now use proxies that require authentication. This was achieved by using selenium-wire instead of regular selenium. It has a couple of useful additions that made this possible.

I have also fixed locked accounts emails not being sent.

### CODE REVIEW

**Comment by dmarts05** [comment]
> What's wrong?
> 

Even though it worked in my desktop, it crashed both my two servers. I'm still figuring out why. I'll reopen the pull request as soon as I fix it.

**Comment by MehdiRtal** [comment]
Maybe the proxy format? It should be user:pass@ip:port

**Comment by dmarts05** [comment]
I think that the problem has something to do with selenium-wire. I used
that same format.

**Comment by MehdiRtal** [comment]
I've used selenium-wire before and it worked just fine, what was the problem?

**Comment by dmarts05** [comment]
It gets stuck ensuring login with bing.

**Comment by dmarts05** [comment]
I have figured out the problem. My servers don't have any kind of display server and it is a must when using selenium-wire. I'll have to find another solution... This looks like something that could actually work: [](https://stackoverflow.com/questions/68583341/selenium-proxy-with-authentication)

**Pull request closed without merging**
